apiVersion: v1

kind: Service

metadata:

  name: user-service-http

spec:

  selector:

    name: user-service

  type: NodePort

  ports:

    - protocol: TCP

      port: 9001

      targetPort: 9001

      nodePort: 31000

      name: user-service-tcp
