apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  ports:
    - port: 8078 # the port that this service should serve on
      name: http
      # the container on each pod to connect to, can be a name
      # (e.g. 'www') or a number (e.g. 80)
      targetPort: 9091
      protocol: TCP
  selector:
    name: user-service